version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ./.env
    depends_on:
      redis:
       condition: service_healthy

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 10s
            retries: 120